# backend editor ajax routes
-
  name: 'H5P Backend Editor AJAX'
  uriPattern: 'neosh5p/editor'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Backend\EditorAjax'
    '@action': 'index'
-
  name: 'H5P Backend Editor AJAX - content type cache'
  uriPattern: 'neosh5p/editor/content-type-cache'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Backend\EditorAjax'
    '@action': 'contentTypeCache'
-
  name: 'H5P Backend Editor AJAX - library install'
  uriPattern: 'neosh5p/editor/library-install{queryString}'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Backend\EditorAjax'
    '@action': 'installLibrary'
-
  name: 'H5P Backend Editor AJAX - single library details'
  uriPattern: 'neosh5p/editor/libraries{queryString}'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Backend\EditorAjax'
    '@action': 'libraryDetails'
  httpMethods: ['GET']
-
  name: 'H5P Backend Editor AJAX - multiple libraries'
  uriPattern: 'neosh5p/editor/libraries'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Backend\EditorAjax'
    '@action': 'libraries'
  httpMethods: ['POST']

# frontend ajax routes
-
  name: 'H5P Frontend AJAX - save results'
  uriPattern: 'neosh5p/contentresults/save'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Frontend\ContentResults'
    '@action': 'save'
  httpMethods: ['POST']
-
  name: 'H5P Frontend AJAX - save content user data'
  uriPattern: 'neosh5p/contentuserdata/save/{queryString}'
  defaults:
    '@package': 'Sandstorm.NeosH5P'
    '@controller': 'Frontend\ContentUserData'
    '@action': 'save'
    'queryString': 'contentId=:contentId&dataType=:dataType&subContentId=:subContentId'
  httpMethods: ['POST']
