Sandstorm:
  NeosH5P:
    h5pPublicFolder:
      # URL of the h5p public folder. Can be absolute or relative to the base Uri.
      url: &h5pPublicFolderUrl '/_Resources/Static/H5P/'
      # File path of the h5p public folder.
      path: &h5pPublicFolderPath '%FLOW_PATH_WEB%/_Resources/Static/H5P/'
      subfolders:
        # subfolder for content. Must be named "content" for now, because H5P expects this.
        content: &h5pContentSubfolderName 'content'
        # subfolder for libraries. Must be named "libraries" for now, because H5P expects this.
        libraries: &h5pLibrarySubfolderName 'libraries'
        # Directory where the H5P core assets (from 3rd party package) are published to.
        core: &h5pCoreSubfolderName 'h5p-core'
        # Directory where the H5P editor assets (from 3rd party package) are published to.
        editor: &h5pEditorSubfolderName 'h5p-editor'
    # These can be generated as ConfigSettings by the flow command
    # ./flow h5p:generatedefaultconfigsettings.
    defaultConfigSettings:
      send_usage_statistics: false
      track_user: true
      save_content_state: true
      save_content_frequency: 10
      hub_is_enabled: true
      enable_lrs_content_types: true
      # content display options
      frame: false
      export: false
      embed: false
      copyright: false
      icon: false

    # Setting for the H5PCore->aggregateAssets switch. If set to TRUE, H5P triggers the generation of
    # aggregated assets (CachedAsset) for each content element.
    aggregateAssets: true
    # Set to true to enable the export functionality.
    # !!! Not implemented yet !!!
    enableExport: false

Neos:

  Neos:
    modules:
      'h5p':
        label: 'H5P Rich Content'
        controller: 'Sandstorm\NeosH5P\Controller\Backend\MainController'
        description: 'Contains modules for managing H5P objects.'
        icon: icon-flash
        submodules:
          content:
            label: 'H5P Content'
            controller: 'Sandstorm\NeosH5P\Controller\Backend\ContentController'
            description: 'Create, edit and manage H5P content elements.'
            icon: icon-check-square
            actions:
              new:
                label: 'New H5P Content'
                title: 'Create new H5P content element'
          library:
            label: 'H5P Libraries'
            controller: 'Sandstorm\NeosH5P\Controller\Backend\LibraryController'
            description: 'Manage H5P libraries, get upgraded versions, and update the H5P hub cache.'
            icon: icon-book
          results:
            label: 'H5P User Results'
            controller: 'Sandstorm\NeosH5P\Controller\Backend\ResultsController'
            description: 'View and delete user results for H5P content elements.'
            icon: icon-flag-checkered
          administration:
            label: 'H5P Administration'
            controller: 'Sandstorm\NeosH5P\Controller\Backend\AdministrationController'
            description: 'Make administrative settings for H5P.'
            icon: icon-cogs


  Flow:
    # We need the tag "@variable" as an ignored annotation, because otherwise parsing of the
    # H5PFrameworkInterface causes a reflection error
    reflection:
      ignoredTags:
        'variable': true

    mvc:
      routes:
        'Sandstorm.NeosH5P':
          position: 'start'

    resource:
      storages:
        h5pLibraryStorage:
          storage: 'Sandstorm\NeosH5P\Resource\Storage\ExtractedH5PLibraryStorage'
          storageOptions:
            publishingSubfolder: *h5pLibrarySubfolderName
            resourceGetterMethod: 'getZippedLibraryFile'
            itemFolderNameMethod: 'getNameAndVersionString'
        h5pCoreStorage:
          storage: 'Sandstorm\NeosH5P\Resource\Storage\H5PPackageFileStorage'
          storageOptions:
            path: '%FLOW_PATH_PACKAGES%Libraries/h5p/'
            library: *h5pCoreSubfolderName
            subfolders:
              - 'fonts'
              - 'images'
              - 'js'
              - 'styles'
        h5pEditorStorage:
          storage: 'Sandstorm\NeosH5P\Resource\Storage\H5PPackageFileStorage'
          storageOptions:
            path: '%FLOW_PATH_PACKAGES%Libraries/h5p/'
            library: *h5pEditorSubfolderName
            subfolders:
              - 'ckeditor'
              - 'images'
              - 'language'
              - 'libs'
              - 'scripts'
              - 'styles'

      collections:
        h5p-libraries:
          storage: 'h5pLibraryStorage'
          target: 'h5pLibraryTarget'
        h5p-core-files:
          storage: 'h5pCoreStorage'
          target: 'h5pCoreTarget'
        h5p-editor-files:
          storage: 'h5pEditorStorage'
          target: 'h5pEditorTarget'

      targets:
        h5pLibraryTarget:
          target: 'Neos\Flow\ResourceManagement\Target\FileSystemTarget'
          targetOptions:
            path: *h5pPublicFolderPath
            baseUri: *h5pPublicFolderUrl
            subdivideHashPathSegment: false
        h5pCoreTarget:
          target: 'Neos\Flow\ResourceManagement\Target\FileSystemTarget'
          targetOptions:
            path: *h5pPublicFolderPath
            baseUri: *h5pPublicFolderUrl
            subdivideHashPathSegment: false
        h5pEditorTarget:
          target: 'Neos\Flow\ResourceManagement\Target\FileSystemTarget'
          targetOptions:
            path: *h5pPublicFolderPath
            baseUri: *h5pPublicFolderUrl
            subdivideHashPathSegment: false
