Neos:
  Neos:
    modules:
      'h5p':
        label: 'H5P Rich Content'
        controller: 'Sandstorm\NeosH5P\Controller\Backend\MainController'
        description: 'Contains modules for managing H5P objects.'
        icon: icon-flash
        submodules:
          content:
            label: 'H5P Content'
            controller: 'Sandstorm\NeosH5P\Controller\Backend\ContentController'
            description: 'Create, edit and manage H5P content elements.'
            icon: icon-check-square
            actions:
              new:
                label: 'New H5P Content'
                title: 'Create new H5P content element'
          library:
            label: 'H5P Libraries'
            controller: 'Sandstorm\NeosH5P\Controller\Backend\LibraryController'
            description: 'Manage H5P libraries, get upgraded versions, and update the H5P hub cache.'
            icon: icon-book
          results:
            label: 'H5P User Results'
            controller: 'Sandstorm\NeosH5P\Controller\Backend\ResultsController'
            description: 'View and delete user results for H5P content elements.'
            icon: icon-flag-checkered
          administration:
            label: 'H5P Administration'
            controller: 'Sandstorm\NeosH5P\Controller\Backend\AdministrationController'
            description: 'Make administrative settings for H5P.'
            icon: icon-cogs


  Flow:
    # We need the tag "@variable" as an ignored annotation, because otherwise parsing of the
    # H5PFrameworkInterface causes a reflection error
    reflection:
      ignoredTags:
        'variable': true


    resource:
      storages:
        h5pLibraryStorage:
          storage: 'Sandstorm\NeosH5P\Resource\Storage\ExtractedH5PFileStorage'

      collections:
        h5p:
          storage: 'h5pLibraryStorage'
          target: 'localWebDirectoryH5PTarget'

      targets:
        localWebDirectoryH5PTarget:
          target: 'Neos\Flow\ResourceManagement\Target\FileSystemTarget'
          targetOptions:
            path: '%FLOW_PATH_WEB%_Resources/Static/H5P/'
            baseUri: '_Resources/Static/H5P/'
            subdivideHashPathSegment: false
